downstream_package_name: oscap-anaconda-addon
upstream_package_name: oscap-anaconda-addon
specfile_path: oscap-anaconda-addon.spec

actions:
  get-current-version:
  - bash -c "grep '^\s*VERSION\s*=\s*' Makefile | sed 's/VERSION\s*=\s*//'"

srpm_build_deps:
  - bash

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - centos-stream-8

