name: Gating
on:
  push:
    branches: [ rhel9-branch ]
  pull_request:
    branches: [ rhel9-branch ]
jobs:
  validate-rhel9:
    name: Unit Tests on CentOS Stream 9 (Container)
    if: github.ref == 'refs/heads/rhel9-branch' || github.event.pull_request.base.ref == 'rhel9-branch'
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    steps:
      - name: Install Deps
        run: dnf install --enablerepo=crb -y make anaconda openscap-scanner openscap-python3 python3-pytest python3-pycurl
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make unittest
