name: Gating
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  validate-fedora:
    name: Unit Tests on Fedora 33 (Container)
    runs-on: ubuntu-latest
    container:
      image: fedora:33
    steps:
      - name: Install Deps
        run: dnf install -y make anaconda openscap-python3 python3-cpio python3-mock python3-pytest python3-pycurl
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make unittest