name: Gating
on:
  push:
    branches: [ rhel8-branch ]
  pull_request:
    branches: [ rhel8-branch ]
jobs:
  validate-rhel8:
    name: Unit Tests on Fedora 32 (Container)
    if: github.ref == 'refs/heads/rhel8-branch' || github.event.pull_request.base.ref == 'rhel8-branch'
    runs-on: ubuntu-latest
    container:
      image: fedora:32
    steps:
      - name: Install Deps
        run: dnf install -y make anaconda openscap-scanner openscap-python3 python3-cpio python3-pytest python3-pycurl
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make unittest
