name: Gating
on:
  push:
    branches: [ rawhide ]
  pull_request:
    branches: [ rawhide ]
jobs:
  validate-rawhide:
    name: Unit Tests on Fedora (Container)
    if: github.ref == 'refs/heads/rawhide' || github.event.pull_request.base.ref == 'rawhide'
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y make anaconda python3-pytest python3-pycurl openscap-scanner
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make unittest
