name: Gating
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate-master:
    name: Unit Tests on Fedora Rawhide (Container)
    if: github.ref == 'refs/heads/master' || github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    container:
      image: fedora:35
    steps:
      - name: Install Deps
        run: dnf install -y make anaconda python3-pytest python3-pycurl openscap-scanner
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make unittest
